### ISSUE TITLE
I believe this has stopped working, it stops after 3-4 rerolls

### ISSUE THREAD

**Issue by 08wckster08** [ajseward/Ascension_Weakauras#3]
it doesnt stop on quality and i cant seem to add a name to stop on either. maybe it was broke with the recent update? or maybe im too O.o to learn how to use it properly?

**Comment by ajseward** [comment]
Can't reproduce this issue. Had it stop on both specific enchants and quality, using gold or runes.

Try deleting and fresh importing the weakaura?

![image](https://user-images.githubusercontent.com/16847730/142754307-904d1a79-804f-4215-81a8-3a94aedbda9c.png)

Make sure you're linking the enchant or typing the name properly and there's no leading or trailing spaces.

Esnure if you're using gold (and want to use gold) that you check the `Can Use Gold` checkbox, or else the button will only work once and stop (since it won't spam re-roll for gold).

![image](https://user-images.githubusercontent.com/16847730/142754337-18d8ba49-2cec-45ff-83a5-feca9ae96916.png)

you can add an enchant by clicking this green + button and shift-clicking an enchant from the collection into the `Enchant Name` field.


Feel free to re-open if you continue having issues and know how to reproduce.
